### PR TITLE
Package

### PR DESCRIPTION
**Pull request by aribrill**
Refactor the code into a Python package named sctcamsoft. This will allow the server, GUI, and mock code to import from each other as Python modules without having to be in the same directories.

### CODE REVIEW

**Comment by aribrill** [comment]
I've pushed an additional commit that better integrates the mock server into the standard code. You can run the server using the `--mock` command line option to enable that mode, with the mock hardware settings contained in the configuration using the key `mock` under each device. The reason I did this is because I realized that setting up the code as a package breaks the relative import that was being used to pass in the mock hardware settings.

**Comment by jakedp7** [comment]
@aribrill I seem to be having issues with install. I pulled this branch and followed the steps in the README's installation section. However, upon a `pip install`, I get this:
```
(sctcamsoft) C:\..\sct-slow-control>pip install --upgrade sctcamsoft
Collecting sctcamsoft
  Could not find a version that satisfies the requirement sctcamsoft (from versions: )
No matching distribution found for sctcamsoft
```
This may just be my inexperience with python's module system, but am I missing anything here? I'm on conda 4.4 and Windows 10, and I installed conda env as described in the README.

**Comment by aribrill** [comment]
Whoops, the instructions were wrong - please check the updated README.

**Review by jakedp7 — APPROVED** [review]
Looks great, I'm very happy to not have to do the janky path-manipulation stuff for imports now.

**Pull request merged**
